---
$:
  preprocess:
    '$.coverage.compare.storage.options.1.region': 'eval'
    '$.coverage.compare.storage.options.1.accessKeyId': 'eval'
    '$.coverage.compare.storage.options.1.secretAccessKey': 'eval'
    '$.cache.options.1.region': 'eval'
    '$.cache.options.1.accessKeyId': 'eval'
    '$.cache.options.1.secretAccessKey': 'eval'
    '$.codeclimate.token': 'eval'
    '$.snyk.token': 'eval'
  cache:
    driver: 's3'
    options:
      - 's3://travis-metadata/cache/MitocGroup/deep-microservices-helloworld'
      -
        region: 'process.env.AWS_DEFAULT_REGION'
        accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
        secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
  npm:
    scripts: []
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?backend(\/?$)?/i
      - /^(.*\/)?frontend(\/?$)?/i
      - /^(.*\/)?node_modules(\/?$)?/i
  test:
    mocha:
      options:
        check-leaks: true
        retries: 2
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~
  coverage:
    pattern:
      - /.+\.js$/i
    ignore:
      - /.+\.spec\.js$/i
    reporters:
      text-summary: ~
      lcovonly:
        file: ./coverage.lcov
    compare:
      negative-delta: 1
      storage:
        driver: 's3'
        options:
          - 's3://travis-metadata/coverage/MitocGroup/deep-microservices-helloworld'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
  codeclimate:
    token: 'process.env.CODECLIMATE_REPO_TOKEN'
  snyk:
    token: 'process.env.SNYK_API_TOKEN'

### Add other modules here...
test-microservice:
  root: src/deep-helloworld
