language: node_js
sudo: false
node_js:
  - '4.3'
  - '4.4'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin/deepify
    - $(npm config get prefix)/bin/jspm
    - $(npm config get prefix)/bin/karma
    - $(npm config get prefix)/bin/_mocha
    - $(npm config get prefix)/bin/istanbul
    - $(npm config get prefix)/bin/istanbul-combine
    - $(npm config get prefix)/bin/codacy-coverage
    - $(npm config get prefix)/bin/protractor
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - secure: 
        HkST7Rqo02BFYp3+XGBzz7fhsKxwxSzr2EeTphbj+8Xa5kjTDUlDInLdrzoKfKK/zJy6njgZp4q561KV3L6HEHlnNjy5e4co1GgkXwrjOsXV+r32H8PHAMvbDCJyOxgERtPxiryfXkmLBkyWhlebAmtyY1Op/O/qQajvQPIboTbDP5awqXyAF/Gitbal88K8fwgHmE/mC9A5MPOttL6PagKkxAiOtE4Z5LuJ13yXHGmJ4KilhfcSw/so0NyqBBlQww22YbfJIsOAGODSlWep9HTo1oS9mZnTTLBY7j9HHJStXtP4pZaNCHeNTMKOf1ZedWcvguADDe32dkU6TfxdwkJj7vtXxUBiWyy7JN8fq3pGrgu2Izpe42DSSqA9bgTfP7HbebvECHcrgGZshgDFR3gRo4ihRnjPfTAswEGnPBNTlISGwxRp7c2a7Ao7Ofkz9o+4ArYvP1BmYwOyZ6hKfKx9zTLHnMTfadygcYH8r0t09a5imK3JKcGWABLpUcDRwzUKLigk8j9tkIKgfcclnPI4r7c1pK5E3uQfTln21OrU02bhuwcCL5VgW1MKHS5NZbZu9kSorBqSqb3DBSjsr5GTpHPvovwsW6YmbD/1nBXThlnAga5cyJ84AnWenOWVa+yiq6AezkDo/AZqBeaNguUBrDhoMHM8jSu+dV9FuP0=
    - secure: 
        UKRAvsXLppfNkkwumZFOJyY8tSjBU05eHXED/BLNWvTOWv59I1cp3PQPoKqTO9zf2Fk0hxOgqZJ3UHN3vd1xKUsgTzgrv+uSvXlRmkQc+MS0Fg4QwCm2e1tx8Km4i8S0vDjmN5yMAS23lapd5DRCvLdpHJbbOnbejNahk3JEqQC8XZ3QUqqIuhtOfAsRic+W4vve2KLHYfd5OzM1AD6i8nn855ohlRCm+L/l4UidtT3wDvweAI4D/3GzMYFP75hOVGVplf2tpm4Uz3ZqDqymeZVZYRHsluwKGW4R9wlSYnPhT8BIltYRMc+owCXqbbbGZXxJBtDfX2w9hTHnTyq9aQSyfWkFvZZ2n19H47TgmzomS3dV1zPg1UbrbBWoQoqfrFPFZd46ZCEAt6Cy3DypYL+bn6gUEtRnMhEV2pc9JtOx1o1UVv+BVHeDlR05jwEN3x99KQBi+OJs57Yi2zOJ17akgtWK9Wyl9jBQrdTXuTheSrCHDIdbH8j2a1HAlmwRVMwFlhzX6FSummtOlXC3pkB9GudHp3vgTojjq1OWmu5ekpkGNqSYs6zdwlsxk8kxaly+dh48Wzt5Otm3+JCVBLIOiIBwsaDYRV+ZxDhL4+q0D+nkm8D8wwBeOmHG20CT0kT1c1cRpKaqwXApKdyeSUB+H50uo+Ywuylb9KB70t4=
    - secure: 
        GX20FFqUT/cXVokjXq7xEyCynXie4XfhvapqUMXJb7lCyMl3z+q6fxWzFwhgwRw1pY0fdLmoQ9xWR3044VtJQmXPt5jUYXJaVbPFccRU4kJ4Bh1Hqk24xIJWIdKxa0+eToEa0QCfEbMmDpvMvohWvKc7BBQgszMU9BLsd41lNZmCBU7lQdrZMt1si03UaS41uzy08lAnIHC9Sq1eegY2r3AXsRzPSEcGPn+bgmCncWzm7tqIrmhsC+j+p4alfEubTaGuWZIKyjaPiBbHBh8fjIhpXgznRSp8BrcLsjhv1AhMAeqe+xzUjLeHMNO4h9S2jEpgY8icWrbOR3kQLQpRhV0om1dtzMUGY3nHkzEi3kJ61Z+iDCCTfg2xC125va2JK7f8wTRe33EB9XSlSohA62uGkYDuupIExO7ScvIDvkyZgN8HAGx0eIUZwA1L4+tFYRAW/JwI2choedB8aL8vWs41F7MXyDJnxcDB7t04jCifIMzroqYBKgBI7NENKioA2l13KHzw1vvf9r+nuSI+NGIbzO1DVaz3P+6rYLfCVFnIQ2FQ2pXj7R0Rm30NFgxPcVeFWna3cB18xNRkfJx4fSX3satDAzTMfrUhBVLGMcBZBfKtwvcbXVck7mZR+cRAo0RgX/v1xg2P2Ev6NsUysjUsci10DNnJH9TVHyLErWw=
notifications:
  slack: $(SLACK_TOKEN)
