language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "Cmm5G3r6R/jnA9RnvJTpU7FJE4tMw/MJ+3W5pz+ncMsDA+BGbe0W4HWxgxJbGdJmG0NKBGcw8u0raT2XuzoekMQhWXYZYjEbMtmnQKwBHBSkRZcWuE+/BWFq3bbiJt0MHrWZU64wNX8b+Yq7kPlIZns2ZKwLLxpLbR2p4xRm+5RkFwv9rLV5ckBs13yOsj62XsT3gfgC/IxmhnOsqxAcsPA65q2VZt4HKCpXV3fbUyzQ3UoMgkHYaXe1JVdCR75fgupN8M097u72sePsF1a9QnriWPcNJtctwej4JUpJ48VpR0HFk3BJ+iriKaVsiRBUGaZrHOfni4BswbRH/bg+zB5pXnoxtJf97jiCuErNXpSak4w0Q4WuaqzqjhBbg5cHgSakts83CS6voZKfW+5jT+vj80QHOOB7KdyKUBHJT33060J6dlM2QawIygxHfhkcPW2oevfImRlB3eirZVwUmzXwJAKFxwJonWevw4OjW1NDW2Ime7zwJ5PTQB27sjElVtmIYn2nIiOj74njghgnWArW2RzumosiRNi7hqwAsNwVL16IdyU6gO/ixGlhaRXiOFjKFkGBeROBkLvekNJHdwNvjVuDz8HXle5xszjTepNLe3GfkB0G5vplsuY7BPqoDntH18CGS4ijr08vXf+G06/oKk9DwwmZmmTSuuzrrdw="
    # SNYK_API_TOKEN=[secure]
    - secure: "H1iGra/80UINdaMk4i3jJ8BINEa09iVr6r/GIWS8kSmoBRR8mS9E2858gbyNmbmCcrYmftbqf1lK/YnvRkU+eCOfZ3pmzZeRb19KftgwMNgvKhx/JyM/YAz3myucnpVnunUUhaITbyR5Pcmn8TzPbcDOpqwH5S3VSIiU80X8jrRMnnqxtXpPVpEoM5sl3Xpv/jYiWMCFyA9Mhmil3llSB4T9pcsnia1kuYK9WIDwtmTGwmRQCqxiSytA3IElt0zL+ClpFXiIbmmJCpvysL8Vzdx8IAkVamvKguTVARrwA8wCzfnRmf2lQej2xdh/I4VuJSF4tF9ylTuGEYaNf7Fk/SSfq3MhEhCCuqNh7xCTWvwNHFA0MCmMvpgd8VfseI+tsCK344PNHYDnYjGpW9is4gOg9lp1vvD9hq+WXAfwByf+vK6aYIpr+Ue8gU9SC7X2GiCfPBG4WXh9l48nBBWtw5PfPUPGmCco0v2Z3D8q9276uAA01AFNLrHfi3ao0tGd78n5cA20P6RSA42c+D2hRgOXAaWKIQPuzzmElCe1q1hn2zPWC0kxdJDfA93mn8ZDLdpAvWYPOc1P1pF9F/iIz8ZJf/sxQh/zK8O49bUT7gUJXDTtcbtPXhlmFDC9sRbadMbe+i8nuWNYSDcnSQIhf/nLqnI60NnvDlGs+kbXv8g="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "UJydr2K523XU4Rh7lwP/dlU3ZlXbwDY75qZ1rgvzM7abZcLcJX6WhRlngcKTXo3YALbmeB6kj268NqYRZrYGC/p9/2nChygYXhpYR28O3Fq2Y3PqEI4TDTmW1+9XwXSiaaK8BBCgdHqHlj8quTnYMfx8syHqD8e3eL6weHy4pJ9HWaN4jNZDLZTLFBG4umF05cGxfH1DiilCFRx3kJMrr/w+VxSjykxdNPJmZg5AudR2fQcnhDuv6ejrfjQmmUl5oWFqqcXFt/LMhyAU3V70yLhWHYx7iv3Pw24vlQb3LDrQSbR/qRqD9jZfW8z18AV5xYfRpMcd5wgOY1E9C+L0rNBKRRyY8N1K1FJYmSB/kotC5KLe5pc/LHIWb+KDrBkTSKIJze8ymp2kOkHAxxAGsVR9pSW5TjAJzJb6GwBV8OkzAZrDiEvJynzIxhjGfrmHiq0W/UDZ6DqI3B2QGT87Tk8Rlr/6CRXPh3zui7kfm3ul7Y5O12fUlfSa5Ss1ciRh9v0W7cY8W0C8ORR4xRg07G29eiY70NF42LlmhZ9KvxIg7aG4zhhqsVzlkBegSRCTDwOzry9zYhrtol30D/7VqjDzC/pxuCgVTgIqv+rv2MSB+7WWnQ4smQi05bMiJQXxslsWf+Nh+HKTc/WBYEZJW2dc4U39SQSoqkqZFZN1s6o="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "1a/b8j/cH9Wl2xxJb+nfydzykIMth50JA66hZwFddfRYeGoWXJ5UdazmLFuepQUzxj6xkdWLl5TY0BH6QJYGwY8YC/Kb3/QsO3NEcKq3IngLkrFK6m6QSJSSf3PhnkWGONRn8Mj4Lgc3ifWxhG8iZqCruLQE4fCNquHhUpA1IqVyaxKuRipRh6RO3KDF5sSuHgZZpV5r7plTrnjtiyKydgsmVbEQCKySNra6C+T6wpdw6oD8PhTacSZahSvzTe7nfmXDpkSZxv9upXv2P1bokNnAP9NHRoc8spE5PP01VHyoaiGK3zdzb2FweEoybJ8K4c6IJR/3qVDpyxVBqfATCUmUl3ZqdJ+0yaSAFc4D3eL2HHw0roO0tfkbmliY81Be0zrgkoes+hwDXSb9nicvCjRy49SGOGj570FJ/DaQEQwHoH38ciIs0RozPSNQHBn+3sx7+4th8a4uhHr8PMhrvR4QLKkkkHEMBpYXtj05BdytYjifmatsAR7g5IbdU7yGKNYD4Sl0Zi08oHvwRgR3HkN7DjJH+JatvD2h3RK8+76nBoN5lLmOj+bLtYcVslCmeguotr+r3Bvq3o3zbIpTnL60o026YnNdqxOxNOCnb1i6CEwGmsYEKWPi2Dg9M4VidzmSgzzi7oNQipINv6PxgM3+v93TWHICP3eMokqFwFI="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "BBcLjEgElIGu0t+GYgJ4s4d62HUKIs45uyrXLEFaC8Tj93EA4s13Tei30h9m+BwiHG9FKDbOXfckMYDw/1O7DCss4ppisNss9ULwojuBUhB9RiZBYqFlvBEhXJRAH4Hc/EInGj9/etKd5vDzTwrb7fOSB/L+ZqYivW0Db2zZLf9G6qaCCuoyJWMAqQpPrQ0bY7KRUcMYJbylPFPNbwcbiVhTrQZ6VdFv0Sipnrj/ZLhBJym+W0SRSSO1IktCivJX//WrIUpdY2RfjD4rcg+85hIrJi7tsCi/g2ymqNJwVJhBBqvy4ijDW0nAYNRt54J9JYIPVeM45Mhi6oBBQn5CD+6erdmDI93wSf0rXVd8ONTG7/aj8pbpwfS/EfUOXh4g2DF1EOH4u5DTjg3Jn8RHoDuGWenUUIKURkGS/avnh1nM20vrfwkmaCa0oqsWA2y7CVfaZBOJ40GsPLNxXxT383RrlbcFAXqPknjmJSudPYp5Se9hEFf6fOEkjdBb4GvDBbCk9o2jDdDHIXn/0QWbtpWvI0pJHRWXbHrHeUYwzpiBKuP5LkX1rQYr8Sn0jA6UwXfy2ZGJYdsnNgmxEWSlHdgCyjzfpqRYtLu+xpo2gwjenmJfd4GhQJ2ylxMb2qllOTmVAenAiHYloHeFrZLr/E5MyEcopoQG9ZdqzQUlI/k="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
