language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "Cmm5G3r6R/jnA9RnvJTpU7FJE4tMw/MJ+3W5pz+ncMsDA+BGbe0W4HWxgxJbGdJmG0NKBGcw8u0raT2XuzoekMQhWXYZYjEbMtmnQKwBHBSkRZcWuE+/BWFq3bbiJt0MHrWZU64wNX8b+Yq7kPlIZns2ZKwLLxpLbR2p4xRm+5RkFwv9rLV5ckBs13yOsj62XsT3gfgC/IxmhnOsqxAcsPA65q2VZt4HKCpXV3fbUyzQ3UoMgkHYaXe1JVdCR75fgupN8M097u72sePsF1a9QnriWPcNJtctwej4JUpJ48VpR0HFk3BJ+iriKaVsiRBUGaZrHOfni4BswbRH/bg+zB5pXnoxtJf97jiCuErNXpSak4w0Q4WuaqzqjhBbg5cHgSakts83CS6voZKfW+5jT+vj80QHOOB7KdyKUBHJT33060J6dlM2QawIygxHfhkcPW2oevfImRlB3eirZVwUmzXwJAKFxwJonWevw4OjW1NDW2Ime7zwJ5PTQB27sjElVtmIYn2nIiOj74njghgnWArW2RzumosiRNi7hqwAsNwVL16IdyU6gO/ixGlhaRXiOFjKFkGBeROBkLvekNJHdwNvjVuDz8HXle5xszjTepNLe3GfkB0G5vplsuY7BPqoDntH18CGS4ijr08vXf+G06/oKk9DwwmZmmTSuuzrrdw="
    # SNYK_API_TOKEN=[secure]
    - secure: "H1iGra/80UINdaMk4i3jJ8BINEa09iVr6r/GIWS8kSmoBRR8mS9E2858gbyNmbmCcrYmftbqf1lK/YnvRkU+eCOfZ3pmzZeRb19KftgwMNgvKhx/JyM/YAz3myucnpVnunUUhaITbyR5Pcmn8TzPbcDOpqwH5S3VSIiU80X8jrRMnnqxtXpPVpEoM5sl3Xpv/jYiWMCFyA9Mhmil3llSB4T9pcsnia1kuYK9WIDwtmTGwmRQCqxiSytA3IElt0zL+ClpFXiIbmmJCpvysL8Vzdx8IAkVamvKguTVARrwA8wCzfnRmf2lQej2xdh/I4VuJSF4tF9ylTuGEYaNf7Fk/SSfq3MhEhCCuqNh7xCTWvwNHFA0MCmMvpgd8VfseI+tsCK344PNHYDnYjGpW9is4gOg9lp1vvD9hq+WXAfwByf+vK6aYIpr+Ue8gU9SC7X2GiCfPBG4WXh9l48nBBWtw5PfPUPGmCco0v2Z3D8q9276uAA01AFNLrHfi3ao0tGd78n5cA20P6RSA42c+D2hRgOXAaWKIQPuzzmElCe1q1hn2zPWC0kxdJDfA93mn8ZDLdpAvWYPOc1P1pF9F/iIz8ZJf/sxQh/zK8O49bUT7gUJXDTtcbtPXhlmFDC9sRbadMbe+i8nuWNYSDcnSQIhf/nLqnI60NnvDlGs+kbXv8g="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "UJydr2K523XU4Rh7lwP/dlU3ZlXbwDY75qZ1rgvzM7abZcLcJX6WhRlngcKTXo3YALbmeB6kj268NqYRZrYGC/p9/2nChygYXhpYR28O3Fq2Y3PqEI4TDTmW1+9XwXSiaaK8BBCgdHqHlj8quTnYMfx8syHqD8e3eL6weHy4pJ9HWaN4jNZDLZTLFBG4umF05cGxfH1DiilCFRx3kJMrr/w+VxSjykxdNPJmZg5AudR2fQcnhDuv6ejrfjQmmUl5oWFqqcXFt/LMhyAU3V70yLhWHYx7iv3Pw24vlQb3LDrQSbR/qRqD9jZfW8z18AV5xYfRpMcd5wgOY1E9C+L0rNBKRRyY8N1K1FJYmSB/kotC5KLe5pc/LHIWb+KDrBkTSKIJze8ymp2kOkHAxxAGsVR9pSW5TjAJzJb6GwBV8OkzAZrDiEvJynzIxhjGfrmHiq0W/UDZ6DqI3B2QGT87Tk8Rlr/6CRXPh3zui7kfm3ul7Y5O12fUlfSa5Ss1ciRh9v0W7cY8W0C8ORR4xRg07G29eiY70NF42LlmhZ9KvxIg7aG4zhhqsVzlkBegSRCTDwOzry9zYhrtol30D/7VqjDzC/pxuCgVTgIqv+rv2MSB+7WWnQ4smQi05bMiJQXxslsWf+Nh+HKTc/WBYEZJW2dc4U39SQSoqkqZFZN1s6o="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "Y+dre3gjTxTLt4RBApmgj9GhJCYRcixf5Mo66640vfmsLFBCyKIFv0Z08zNVMJAt7s+wMILEiTRbb8NOeHtpfgXXrtGr0wZljA9zamyAtN5Cwh5e5csJvPJ9hp0r0JbB5z8wPNC60OL0uAomjKABDaWAdldgNvx3TpYBDbgvgym3UkS3TDfvQKYb6xe8t4+vPlcnXEJ4ed1t2kd8/8LITHs8Ao+jcJo5/j1Yy8YC7W3Ma28TUm5sD0KvnqiJyc5aHo3aD+DrVC1GBdwH4+QDiq2b9lzhsREVihj66g4Xij0F1Zi5PVgyOjzyfISRrgvfP9M+VTqQ/hdsV1NMmqepEoZHfPgMVLff7fwBkZu42OZB7R0gfv9EqXQgrDdw5mU/2MXjIu7t7HSkWvoV8LVezPQkhBKg9Z9/Pt9iY60YzFZMbxSmPYgPZrMItcOzb7uy39kpSD2V/0IcZ9P2nwNubZKYvo3pIxjiiE8RjMR/F6vNgQNgEUO/FwZSeSHStehC8+Ghz0DD3NK8CQDP1Xnv14T3FA47xnk4JUozP4DkeBBqICqxVdQ0PnX9qX944woEG+Zase9Rt+R+rYWEr14hEsraLc2rel/CYKgA0r///OeqenwVfyTkUpNXZ0l+/eR5JUaRre8SkTNcWoGNs0vOWlB2EF15GXyzXlw/U7oC5y0="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "Up7a5WbQdEyfBXB7DJ8b6FeiNnu8jhozm3Q05Yz0wf/sC2DnQWYFm0940IhKW4S6psEwN26FMNOnzYgJ7OrGKEEf/PfFyIO57DqtyhukSxCxIAE/1TrUpGiIJSn94PZwGuSewlxgKfUzVoHIL1tB3BQCSqQj5l/0i4/MAaUQY6X1geM0016Quby4/BHf4yYuUgYGsZsQGtRt9K8sCq8I3Z8BpfJ3tg7TsJOwVRX5PbXuxOlehnz9T4ob5qKWk99x8ARsOBsJTXcO4VUivEdLPT/dC95dJXVFIj2oNbRkP2Vn7XHGE6AMi2ESt9uT/QkIK6i/0I2kcD8rEG8ohTSGvHt742V6kP/ueVu2KmtuWQc7Lk9oTbyIiilzEJ2ubB0Ey9hz1vTY4/aJbMaIK/oHvPPYJZJdkAYG4PJHMb0E9SPOe8gD9orVKgTwnrhVnZ6t6NjMrSDFqUq+DNeKsGSigO7Lvkxo/BVwrtTr/O52/Qm4+ZcQxArjKZDlAjk0ZsoYkcLn3cGyMogeU09ppXhyJVf1qIIvnCi05eEzyomAZQXn4KAYnKJI5k3dloKI3/+v34fBQRDk0eed4U93UumY6aZdT4LCN8fOz4E/N3orVeA1edolS6nBTlyWj5L7fUtxDOlacc3sYrIiWth/j222VPbVmX7XSXFUvMpEqbeiADQ="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
