language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - secure: 
        HkST7Rqo02BFYp3+XGBzz7fhsKxwxSzr2EeTphbj+8Xa5kjTDUlDInLdrzoKfKK/zJy6njgZp4q561KV3L6HEHlnNjy5e4co1GgkXwrjOsXV+r32H8PHAMvbDCJyOxgERtPxiryfXkmLBkyWhlebAmtyY1Op/O/qQajvQPIboTbDP5awqXyAF/Gitbal88K8fwgHmE/mC9A5MPOttL6PagKkxAiOtE4Z5LuJ13yXHGmJ4KilhfcSw/so0NyqBBlQww22YbfJIsOAGODSlWep9HTo1oS9mZnTTLBY7j9HHJStXtP4pZaNCHeNTMKOf1ZedWcvguADDe32dkU6TfxdwkJj7vtXxUBiWyy7JN8fq3pGrgu2Izpe42DSSqA9bgTfP7HbebvECHcrgGZshgDFR3gRo4ihRnjPfTAswEGnPBNTlISGwxRp7c2a7Ao7Ofkz9o+4ArYvP1BmYwOyZ6hKfKx9zTLHnMTfadygcYH8r0t09a5imK3JKcGWABLpUcDRwzUKLigk8j9tkIKgfcclnPI4r7c1pK5E3uQfTln21OrU02bhuwcCL5VgW1MKHS5NZbZu9kSorBqSqb3DBSjsr5GTpHPvovwsW6YmbD/1nBXThlnAga5cyJ84AnWenOWVa+yiq6AezkDo/AZqBeaNguUBrDhoMHM8jSu+dV9FuP0=
    - secure: 
        UKRAvsXLppfNkkwumZFOJyY8tSjBU05eHXED/BLNWvTOWv59I1cp3PQPoKqTO9zf2Fk0hxOgqZJ3UHN3vd1xKUsgTzgrv+uSvXlRmkQc+MS0Fg4QwCm2e1tx8Km4i8S0vDjmN5yMAS23lapd5DRCvLdpHJbbOnbejNahk3JEqQC8XZ3QUqqIuhtOfAsRic+W4vve2KLHYfd5OzM1AD6i8nn855ohlRCm+L/l4UidtT3wDvweAI4D/3GzMYFP75hOVGVplf2tpm4Uz3ZqDqymeZVZYRHsluwKGW4R9wlSYnPhT8BIltYRMc+owCXqbbbGZXxJBtDfX2w9hTHnTyq9aQSyfWkFvZZ2n19H47TgmzomS3dV1zPg1UbrbBWoQoqfrFPFZd46ZCEAt6Cy3DypYL+bn6gUEtRnMhEV2pc9JtOx1o1UVv+BVHeDlR05jwEN3x99KQBi+OJs57Yi2zOJ17akgtWK9Wyl9jBQrdTXuTheSrCHDIdbH8j2a1HAlmwRVMwFlhzX6FSummtOlXC3pkB9GudHp3vgTojjq1OWmu5ekpkGNqSYs6zdwlsxk8kxaly+dh48Wzt5Otm3+JCVBLIOiIBwsaDYRV+ZxDhL4+q0D+nkm8D8wwBeOmHG20CT0kT1c1cRpKaqwXApKdyeSUB+H50uo+Ywuylb9KB70t4=
notifications:
  slack:
    secure: 
      G0ERrlNOeD/XaIja2lV16GdwmezjreoGog22zAbKIBBIwOGlEOcTzmJjUlGAvwpQbWNi85hSs8395S1rIl0jfHalX/g42Rn/eTyidkoGxp0MiLFVTff+26ctEFZPQNcF4fTomgTt1hGl4ETfGp7maowa7zlgLGhAzW5O7CdJ/3l+X9M2OLuMQMoqPpypbgTG9lB22tX/vXGfkPSPV7+5u51q0wvRWL2v4+fq98FIxCkHDmHKHAqSOwQJ3wbhGp7CWTPa5+Rq+mc6LDGa9nxWWbtr0vkWqdaXg2O0Vn7SOxuq3xzsowHq5ujmvKLMq+0px0sweRAN/CTsWCSOoX3dYjQHtQpXzkN9VJJ5RYbbLMTGQUuf18UWYxGjJrnpzQZ5S+YqznKAyu8iuZR3X/i2/XkS0wqL3NB4bk02pr5Lf4MhVhJsoEpR6JuiZ58SrxjLztmpjm8BOGL/3+pQs5bfQaaxrcgCzqdGHs1fmCkDWEHxVGRWFQbFGgr1RYQdDuabYtNqiHntEq8Rdn5cYvnciRg3B77tsHxiasQDSJ43TrOPAgou9+cDfZQ0OYizZI/xLrecIZdcs6+0tYdUX3Sa9V84CEmfvAUGYA8YAOxzghIX8pO33rEDGhgjK28KAXEaku7zjlXvTUqVXeM7a4zqadMeNW2HUnerv6NTozRZqj4=
